### ISSUE TITLE
Loading [MathJax]/extensions/MathEvents.js

### ISSUE THREAD

**Issue by underrated** [icm7216/TWC-MathJax-Plugin#1]
Hi,

I get this message in the bottom left of the page saying:
Loading [MathJax]/extensions/MathEvents.js

This is how it looks like:
![image](https://user-images.githubusercontent.com/3176771/51432629-f83dee80-1c3a-11e9-835d-eedd830cc281.png)

I see it in both Firefox and Chrome on Windows 10.

Do you know how to make this go away?

Thanks!

**Comment by icm7216** [comment]
Hi, @underrated

This plugin uses Mathjax to display mathematical expressions. Probably this is a message from a web browser that tells the user that Mathjax is getting the file. There is no problem if the mathematical expression is correctly displayed.

This is a notification message displayed by the web browser, so this display is not under the control of this plugin.

**Comment by underrated** [comment]
It's not the status bar, it's a div put there by MathJax and it doesn't go away.
You can see it in the DOM inspector, here's a screenshot:
![image](https://user-images.githubusercontent.com/3176771/51472878-0bf06e80-1d7b-11e9-904f-2565393aa007.png)

One workaround for it is to delete it manually from the DOM inspector like this(in Firefox):
![image](https://user-images.githubusercontent.com/3176771/51472923-36dac280-1d7b-11e9-938d-d78eda9d86cb.png)

Chrome has something similar.

Can you think of some way to automate this from the javascript code of TiddlyWiki? I tried using removeChild but it didn't work.

The reason I'm insisting on this is because sometimes I want to print one ore more tiddlers and that thing there shows on the printed paper. I can use the workaround that I showed you but it would be nicer to simply not have that message appear there at all.

**Comment by icm7216** [comment]
@underrated Thank you for teaching me what I mistake.

In my environment these messages will soon disappear. Therefore, the message does not remain on the screen. I confirmed that the `#MathJax_Message` element hidden in the DOM inspector.

![image](https://user-images.githubusercontent.com/16305594/51486355-d2078280-1de3-11e9-9f0e-169d1cff734d.png)

 
You can customize the message line by setting the style of the #MathJax_Message selector.
```
MathJax.Hub.Config({
  styles: {
    "#MathJax_Message": {display: "none"},
  }
});
```

In this plugin, `HubConfig: { ... }`at the MathJax Configuration Options. 

*   oiginal line
```
styles: { ".MathJax": { color:"black"} },
```

*   applied line, Hide the display style of the #MathJax_Message selector
```
styles: { ".MathJax": { color:"black"}, 
          "#MathJax_Message": {display: "none"} },
```

**Comment by underrated** [comment]
Works like a charm. Thanks a lot!
